name: Build, Test and Publish npm

on:
  push:
    branches:
      - master
    paths:
      - 'package.json'

permissions: { }

jobs:
  publish:
    name: Publish npm
    runs-on: ubuntu-latest
    environment: deploy

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Fetch Sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Publish
        run: npm publish --access public
